config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :projects do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  resources :contacts, only: [:new, :create]

  get 'welcome/index'
  root 'welcome#index'

  get "/contact" => "welcome#contact"
  post "/contact" => "welcome#message"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def new
    @comment = @commentable.comments.build
  end

  def edit
    @comment = @commentable.comments.find(params[:id])
  end

  def create
    @comment = @commentable.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @commentable, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        instance_variable_set("@#{@resource.singularize}".to_sym, @commmentable)
        render template: "#{@resources}/show"
      end
    end
  end

  def update
    @comment = @commentable.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @commentable, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = @commentable.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @commentable, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def load_commentable
    @resource, id = request.path.split('/')[1,2]
    @commentable = @resource.singularize.classify.constantize.find(id)
    # same as Post.find(id) or Project.find(id)
  end

  def comment_params
    params.require(:comment).permit(:author, :author_url, :author_email, :user_ip, :user_agent, :referrer, :content, :approved, :commentable_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= form_for([@commentable, @comment]) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2 = pluralize(@comment.errors.count, "error") prohibited this comment from being saved:

      %ul
      - @comment.errors.full_messages.each do |message|
        %li = message

  .field
    = f.label :author
    %br
    = f.text_area :author

  .field
    = f.label :content
    %br
    = f.text_area :content

  #field
    - if policy(@comment).approve?
      = f.label :approved
      = f.check_box :approved

  .actions
    = f.submit

app/views/comments/edit.html.haml
%h1 Editing Comment

= render 'form'

= link_to 'Back', post_path(@commentable)

app/views/comments/new.html.haml
%h1 New Comment

= render "form"

= link_to "Back", posts_path(@post)