config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :projects do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  resources :contacts, only: [:new, :create]

  get 'welcome/index'
  root 'welcome#index'

  get "/contact" => "welcome#contact"
  post "/contact" => "welcome#message"
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :technologies_used, presence: true
  validates :name, length: { in: 4..255 }
  has_many :comments, as: :commentable
  has_attached_file :image,
                    :storage => :s3,
                    :styles => { :thumb => "x100", :medium => "x300"},
                    :s3_credentials => {
                      :bucket => ENV['AWS_S3_BUCKET'],
                      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
                    }
  validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png application/pdf)

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  # protect_from_forgery :only => [:create, :update, :destroy]


  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      format.html do
        if @project.save
          flash[:notice] = "Project has been created."
          redirect_to projects_path
        else
          flash.now[:error] = "Project could not be saved."
          render :new
        end
      end
      format.js do |format|
        @project.save
      end
    end
  end

  def show
    @commentable = @project
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def edit
  end

  def update
    @project.update_attributes(project_params)
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was Successfully updated.' }
      format.js {}
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.js {}
    end
  end

  private

    def project_params
      params.require(:project).permit(:name, :technologies_used, :image)
    end

    def set_project
      @project = Project.find(params[:id])
    end
end

app/views/projects/_form.html.erb
<%= form_for(@project, remote: true) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :technologies_used %><br />
    <%= f.text_area :technologies_used %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

app/views/projects/_project.html.erb
<li class="project" id="<%= dom_id(project) %>">
  <h3><%= project.name %></h3>
  <p><%= project.technologies_used %></p>
  <div class="nav">
    <%= link_to 'Show', project %> |
    <%= link_to 'Edit', edit_project_path(project), remote: true %> |
    <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
  </div>
</li>

app/views/projects/create.js.erb
$("#new_project").remove()
$("#new_link").show()
$("ul").append("<%= j render @project %>")

app/views/projects/destroy.js.erb
$("#<%= dom_id @project %>").remove()

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form" %>

<%= link_to "Cancel", :back %>

app/views/projects/edit.js.erb
$("#<%= dom_id @project %>").html("<%= j render 'form' %>")

app/views/projects/index.html.erb
<h2>My Portfolio</h2>

<ul>
  <%= render @projects %>
</ul>

<br>
<%= link_to 'New Project', new_project_path, id: :new_link, remote: true %>
<%= link_to 'Home', root_path %>

app/views/projects/new.html.erb
<h2>New project</h2>

<%= render "form" %>

<%= link_to 'Back', projects_path %>

app/views/projects/new.js.erb
$("#new_link").hide().after("<%= j render 'form' %>")

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p>Technologies used: <%= @project.technologies_used %></p>
<p>
  <%= image_tag @project.image.url(:thumb) %>
</p>

<br>
<%= link_to 'Back', projects_path %> |
<%= link_to 'Leave a comment', new_project_comment_path(@project) %>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment</th> 
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% policy_scope(@project.comments).each do |comment| %>
      <tr id="<%= dom_id(@project) %>">
        <td><%= comment.author %></td>
        <td><%= comment.content %></td>
        <td><%= comment.approved %></td>
        <td><%= link_to 'Edit', edit_project_comment_path(@project, comment) %></td>
        <% if policy(comment).destroy? %>
          <td><%= link_to 'Destroy', project_comment_path(@project, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/update.js.erb
$("#edit_project_<%= @project.id %>").remove()
$("#<%= dom_id @project %>").append("<%= j render @project %>")