config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :projects do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  resources :contacts, only: [:new, :create]

  get 'welcome/index'
  root 'welcome#index'

  get "/contact" => "welcome#contact"
  post "/contact" => "welcome#message"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  has_many :comments, as: :commentable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # Code added to pass 'Deleting a post' test
  skip_before_action :verify_authenticity_token, only: :destroy
  # GET /posts
  # GET /posts.json
  def index
    @posts = policy_scope(Post)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @commentable = @post
    @comments = @commentable.comments
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        current_user.posts << @post
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, (:published if PostPolicy.new(current_user, @post).publish?))
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <% if PostPolicy.new(current_user, @post).publish? %>
    <div class ="row collapse">
      <div class="small-3 columns">
        <%= f.label :published, class: "right inline", title: "Is this post published?", data: {tooltip: true} %>
        <br>
      </div>

      <div class="small-9 columns">
        <%= f.check_box :published %>
      </div>
    </div>
  <% end %>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %>
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr id="<%= dom_id(post) %>">
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <% if policy(post).update? %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <% end %>
        <% if policy(post).destroy? %>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.present? %>
  <%= link_to 'New Post', new_post_path %> | 
<% end %>
<%= link_to 'Home', root_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="author">
  <b>By:</b>
  <%= @post.author.email %>
</p>

<p id="status">
  <b>Status:</b>
  <%= @post.published? ? "Published" : "Unpublished" %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %> |
<%= link_to 'Leave a comment', new_post_comment_path(@post) %>
<br></br>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment</th> 
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% policy_scope(@post.comments).each do |comment| %>
      <tr id="<%= dom_id(@post) %>">
        <td><%= comment.author %></td>
        <td><%= comment.content %></td>
        <td><%= comment.approved %></td>
        <td><%= link_to 'Edit', edit_post_comment_path(@post, comment) %></td>
        <% if policy(comment).destroy? %>
          <td><%= link_to 'Destroy', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>