config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :projects do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  resources :contacts, only: [:new, :create]

  get 'welcome/index'
  root 'welcome#index'

  get "/contact" => "welcome#contact"
  post "/contact" => "welcome#message"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Tony-Chung.com" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div>
      <% if current_user.present? %>
        Signed in as <%= current_user.email %> Not you?
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> / <%= link_to "Sign in", new_user_session_path %> or
        <%= link_to "Sign in with twitter", user_omniauth_authorize_path(:twitter) %>
      <% end %>
    </div>
    
    <div>
      <%= link_to 'Contact me!', new_contact_path %>
    </div>

    <!-- Flash Notice -->
    <% if flash[:notice] %>
      <div class="alert-box round">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>

</html>